name: csaopt-worker
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numba
  - cudatoolkit
  - boto3
  - arrow
  - click
  - pytest
  - pytest-cov
  - Sphinx
  - coverage
  - coveralls
  - flake8
  - pytest-timeout
  - pytest-mock
  - mypy
  - msgpack-python
  - pip:
    - gputil
    - aiokafka
    - lz4tools
    - xxhash
    - pyhocon
    - sphinxcontrib-napoleon
