name: csaopt-worker
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numba
  - cudatoolkit=8.0
  - boto3
  - pytest
  - pytest-cov
  - Sphinx
  - coverage
  - coveralls
  - flake8
  - pytest-timeout
  - pytest-mock
  - mypy
  - msgpack-python
  - msgpack-numpy
  - pip:
    - gputil
    - dramatiq[redis, watch]
    - pyhocon
    - sphinxcontrib-napoleon
