name: csaopt-worker
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numba=0.40.0
  - cudatoolkit=8.0
  - msgpack-python=0.5.6
  - msgpack-numpy=0.4.3.2
  - pyhocon=0.3.47
  - psutil=5.4.7
  - pip:
    - gputil==1.3.0
    - dramatiq[redis]==1.3.0
